/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clientesdistribuidos;

import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.net.Socket;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import negociodistribuidos.Asignacion;
import negociodistribuidos.Calificacion;

/**
 *
 * @author arand
 */
public class RevisionCalificacion extends javax.swing.JFrame {
    
     final String host = "127.0.0.1";
    final int puerto = 5060;
    private ArrayList<Calificacion> calificaciones;
    Panel padre;
    private int id;
    private Renderer render;
    
    /**
     * Creates new form NewJFrame
     */
    public RevisionCalificacion(Panel padre, int id) {
        this.padre = padre;
        this.id = id;
        this.getCalificaciones();
        this.setLocationRelativeTo(this);
        initComponents();
        this.fillTable();
        //tablaCalificaciones.setDefaultRenderer(Object.class, render);
        
    }
    
    private void fillTable(){
       DefaultTableModel model = (DefaultTableModel) tablaCalificaciones.getModel();
        model.setRowCount(0); 
        
      Object rowData[] = new Object[3];
      for(int i = 0;i<this.calificaciones.size();i++){
          rowData[0] = this.calificaciones.get(i).getCurso();
          rowData[1] = this.calificaciones.get(i).getTareas();
          rowData[2] = this.calificaciones.get(i).getNum();
          model.addRow(rowData);
      }
      
     
    }
    
    private void getCalificaciones(){
         try {
             
            calificaciones = new ArrayList<Calificacion>();
            System.out.println("Iniciando conexion con logica");
            DataInputStream in;
            DataOutputStream out;
            ObjectInputStream inObj;
            
            System.out.println("Socket a logica");
            Socket sc = new Socket(host, puerto);
            in = new DataInputStream(sc.getInputStream());
            out = new DataOutputStream(sc.getOutputStream());
            inObj = new ObjectInputStream(sc.getInputStream());
            System.out.println("Enviando opcion");
            out.writeInt(4);
            System.out.println("Enviando el id");
            out.writeInt(this.id);
             System.out.println("Ando recibiendo el largo del arreglo");
             int size = in.readInt();
             System.out.println(size);
             if(size != 0){
                 System.out.println("ENTRE");
                 while(size > 0){
                     Calificacion cal = (Calificacion) inObj.readObject();
                     System.out.println(cal.getCurso());
                     calificaciones.add(cal);
                     size--;
                 }
             }else{
                 System.out.println("NO HAY CALIFICACIONES");
             }
         } catch (IOException ex) {
             Logger.getLogger(RevisionCalificacion.class.getName()).log(Level.SEVERE, null, ex);
         } catch (ClassNotFoundException ex) {
             Logger.getLogger(RevisionCalificacion.class.getName()).log(Level.SEVERE, null, ex);
         }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCalificaciones = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaCalificaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Curso", "Tareas", "Calificacion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaCalificaciones);

        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(jButton1)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        padre.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaCalificaciones;
    // End of variables declaration//GEN-END:variables
}
